Repository aristotle-mdr/aristotle-metadata-registry, pull requests merged in 2019-11, with the labels that each got.

#1547 Fixed Notification Permissions error.
  assets/package-lock.json
  python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/header.html
  python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py
Labels: ready

#1540 A few improvements
  python/aristotle-metadata-registry/aristotle_mdr/forms/bulk_actions.py
  python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/workgroups/edit.html
  python/aristotle-metadata-registry/aristotle_mdr/views/bulk_actions.py
Labels: ready

#1538 Fixes Status Reversion page not 403ing if insufficient permissions
  assets/package-lock.json
  python/aristotle-metadata-registry/aristotle_mdr/mixins.py
  python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_versions.py
  python/aristotle-metadata-registry/aristotle_mdr/views/views.py
Labels: ready

#1549 Changed settings.
  python/aristotle-metadata-registry/aristotle_mdr/required_settings.py
  python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/de_1_initial_search.html
  python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/dec_1_initial_search.html
Labels: ready

#1542 Added VersionPermission specific checks to API version views
  python/aristotle-mdr-api/aristotle_mdr_api/v4/concepts/tests.py
  python/aristotle-mdr-api/aristotle_mdr_api/v4/concepts/views.py
  python/aristotle-metadata-registry/aristotle_mdr/managers.py
  python/aristotle-metadata-registry/aristotle_mdr/tests/settings/settings.py
  python/aristotle-metadata-registry/aristotle_mdr/views/views.py
Labels: ready

#1551 Improved Status Reversion pages, added testing
  assets/package-lock.json
  python/aristotle-metadata-registry/aristotle_mdr/forms/forms.py
  python/aristotle-metadata-registry/aristotle_mdr/models.py
  python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/registrationHistory.html
  python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/status_history.html
  python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_versions.py
  python/aristotle-metadata-registry/aristotle_mdr/tests/utils.py
  python/aristotle-metadata-registry/aristotle_mdr/views/views.py
Labels: ready

#1553 Added a link deduplicator in ConceptViewPage
  python/aristotle-glossary/aristotle_glossary/models.py
  python/aristotle-glossary/aristotle_glossary/tests/settings.py
  python/aristotle-glossary/aristotle_glossary/tests/tests.py
  python/aristotle-mdr-api/aristotle_mdr_api/v3/views/concepts.py
  python/aristotle-mdr-api/aristotle_mdr_api/v4/tests.py
  python/aristotle-metadata-registry/aristotle_mdr/contrib/custom_fields/models.py
  python/aristotle-metadata-registry/aristotle_mdr/contrib/links/templates/aristotle_mdr/links/link_display.html
  python/aristotle-metadata-registry/aristotle_mdr/contrib/links/tests/test_links.py
  python/aristotle-metadata-registry/aristotle_mdr/contrib/links/utils.py
  python/aristotle-metadata-registry/aristotle_mdr/contrib/serializers/concept_serializer.py
  python/aristotle-metadata-registry/aristotle_mdr/managers.py
  python/aristotle-metadata-registry/aristotle_mdr/views/views.py
Labels: ready

#1565 Added linting github action
  .github/workflows/linting.yaml
Labels: in progress

#1568 Improved GitHub action.
  .github/workflows/check-for-unapplied-migrations.yaml
  .github/workflows/documentation.yaml
  .github/workflows/javascript.yaml
  .github/workflows/linting.yaml
  .github/workflows/python.yaml
  .travis.yml
  docs/requirements.txt
  python/aristotle-metadata-registry/aristotle_mdr/views/comparator.py
Labels: in progress

#1586 Implemented basic functionality.
  python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/forms.py
  python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/create.html
  python/aristotle-metadata-registry/aristotle_mdr/templatetags/aristotle_tags.py
Labels: ready

#1593 Fixed problem with exclamation mark instead of question mark.
  python/aristotle-metadata-registry/aristotle_mdr/contrib/help/templates/aristotle_mdr_help/helpers/custom_field_icon.html
  python/aristotle-metadata-registry/aristotle_mdr/contrib/help/templates/aristotle_mdr_help/helpers/field_icon.html
Labels: ready

#1585 Added permission check
  python/aristotle-metadata-registry/aristotle_mdr/admin.py
  python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/aristotle_mdr/collections/helpers/actionbar.html
  python/aristotle-metadata-registry/aristotle_mdr/perms.py
  python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/actionbar.html
  python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_admin_pages.py
  python/aristotle-metadata-registry/aristotle_mdr/tests/utils.py
  python/comet-indicator-registry/comet/tests/test_comet.py
Labels: ready

#1599 Fixed text.
  python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/user/user_request_endorse.html
Labels: ready

#1595 Fixed template error.
  python/aristotle-metadata-registry/aristotle_mdr/perms.py
  python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/actionbar.html
  python/aristotle-metadata-registry/aristotle_mdr/views/views.py
Labels: ready

#1597 Fixed Reviews titles.
  python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/models.py
  python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/base.html
  python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/user/user_request_accept.html
  python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/user/user_request_cancel.html
  python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/user/user_request_endorse.html
  python/aristotle-metadata-registry/aristotle_mdr/messages.py
Labels: ready

#1527 Url improvements
  Pipfile.lock
  python/aristotle-metadata-registry/aristotle_mdr/contrib/identifiers/urls.py
  python/aristotle-metadata-registry/aristotle_mdr/contrib/identifiers/views.py
  python/aristotle-metadata-registry/aristotle_mdr/contrib/slots/tests.py
  python/aristotle-metadata-registry/aristotle_mdr/contrib/view_history/urls.py
  python/aristotle-metadata-registry/aristotle_mdr/required_settings.py
  python/aristotle-metadata-registry/aristotle_mdr/tests/accessibility.py
  python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_user_pages.py
  python/aristotle-metadata-registry/aristotle_mdr/tests/settings/settings.py
  python/aristotle-metadata-registry/aristotle_mdr/urls/__init__.py
  python/aristotle-metadata-registry/aristotle_mdr/urls/aristotle.py
  python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py
  python/comet-indicator-registry/comet/tests/test_comet.py
  python/comet-indicator-registry/comet/tests/urls.py
Labels: ready

#1573 Supersede gql
  python/aristotle-mdr-graphql/aristotle_mdr_graphql/aristotle_filterset_classes.py
  python/aristotle-mdr-graphql/aristotle_mdr_graphql/aristotle_nodes.py
  python/aristotle-mdr-graphql/aristotle_mdr_graphql/resolvers.py
  python/aristotle-mdr-graphql/aristotle_mdr_graphql/schema/aristotle_mdr.py
  python/aristotle-mdr-graphql/aristotle_mdr_graphql/types.py
  python/aristotle-metadata-registry/aristotle_mdr/managers.py
  python/aristotle-metadata-registry/aristotle_mdr/models.py
Labels: on hold

#1610 Linkendforms error fixes
  python/aristotle-metadata-registry/aristotle_mdr/contrib/links/forms.py
  python/aristotle-metadata-registry/aristotle_mdr/contrib/links/urls.py
Labels: ready

#1616 Fixes users being sent notifications about their own actions
  python/aristotle-metadata-registry/aristotle_mdr/apps.py
  python/aristotle-metadata-registry/aristotle_mdr/contrib/async_signals/notification_events.py
  python/aristotle-metadata-registry/aristotle_mdr/contrib/async_signals/utils.py
  python/aristotle-metadata-registry/aristotle_mdr/contrib/issues/models.py
  python/aristotle-metadata-registry/aristotle_mdr/messages.py
  python/aristotle-metadata-registry/aristotle_mdr/models.py
  python/aristotle-metadata-registry/aristotle_mdr/signals.py
  python/aristotle-metadata-registry/aristotle_mdr/tests/extensions/test_extension_api_disabler.py
  python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_notifications.py
Labels: ready

#1627 Review Request form is used for create and update templates.
  assets/package-lock.json
  python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/forms.py
  python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/create.html
  python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/create_update_review_form.html
  python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/update.html
Labels: ready
